export const planetas = [
    {
        id: 1,
        nome: "Tatooine",
        imagemPlaneta: "assets/images/Tatooine_HTML.png",
        descricao: "Assim como Tatooine é a base árida onde tudo começa, o HTML é o terreno fundamental da web. Simples, resistente e essencial para qualquer jornada galáctica no desenvolvimento.",
        linguagem: "HTML",
        iconeLinguagem: "assets/images/Icone_HTML.png",
        corModal: "linear-gradient(90deg, #384C6E, #736357)",
        x: 60,
        y: 60,
    },
    {
        id: 2,
        nome: "Naboo",
        imagemPlaneta: "assets/images/Naboo_CSS.png",
        descricao: "Naboo, com seus lagos serenos e arquitetura grandiosa, reflete o CSS: a camada que traz harmonia, elegância e as cores suaves para o terreno estrutural do HTML. É a beleza que transcende a base.",
        linguagem: "CSS",
        iconeLinguagem: "assets/images/Icone_CSS.png",
        corModal: "linear-gradient(90deg, #003D5B, #660000)",
        x: 170,
        y: 300,
    },
    {
        id: 3,
        nome: "Coruscant",
        imagemPlaneta: "assets/images/Coruscant_JavaScript.png",
        descricao: "Coruscant, o centro nevrálgico da Galáxia, representa o JavaScript: é a camada de lógica e dinamismo, onde todas as interações e decisões do sistema FrontEnd são orquestradas.",
        linguagem: "JavaScript",
        iconeLinguagem: "assets/images/Icone_JavaScript.png",
        corModal: "linear-gradient(90deg, #20232A, #006400)",
        x: 300,
        y: 150,
    },
    {
        id: 4,
        nome: "Kamino",
        imagemPlaneta: "assets/images/Kamino_React.png",
        descricao: "Kamino, o planeta onde a eficiência é clonada e replicada, espelha o React: a tecnologia que permite construir interfaces complexas através da reutilização de componentes perfeitos e isolados.",
        linguagem: "React",
        iconeLinguagem: "assets/images/Icone_React.png",
        corModal: "linear-gradient(90deg, #5D6D7E, #0D47A1)",
        x: 500,
        y: 40,
    },
    {
        id: 5,
        nome: "Geonosis",
        imagemPlaneta: "assets/images/Geonosis_Angular.png",
        descricao: "Geonosis, com suas vastas forjas e estruturas em colmeia, representa o Angular: o framework robusto e estruturado, ideal para construir aplicações de escala industrial, com arquitetura definida e ferramentas prontas para produção.",
        linguagem: "Angular",
        iconeLinguagem: "assets/images/Icone_Angular.png",
        corModal: "linear-gradient(90deg, #CC5500, #663300)",
        x: 80,
        y: 490,
    },
    {
        id: 6,
        nome: "Lothal",
        imagemPlaneta: "assets/images/Lothal_Tailwind.png",
        descricao: "Lothal, com suas vastas planícies e a base discreta de suas fazendas, é o Tailwind CSS: um framework utilitário que traz eficiência e liberdade para construir estilos complexos diretamente no terreno do HTML.",
        linguagem: "Tailwind",
        iconeLinguagem: "assets/images/Icone_Tailwind.png",
        corModal: "linear-gradient(90deg, #808000, #104E8B)",
        x: 400,
        y: 330,
    },
    {
        id: 7,
        nome: "Zeltros",
        imagemPlaneta: "assets/images/Zeltros_SASS.png",
        descricao: "Zeltros, o mundo das cores vibrantes e do estilo exuberante, representa o Sass: a ferramenta que transforma o CSS básico em uma experiência completa, organizada e cheia de recursos, com variáveis, aninhamento e mixins que elevam a estilização a outro nível.",
        linguagem: "SASS",
        iconeLinguagem: "assets/images/Icone_SASS.png",
        corModal: "linear-gradient(90deg, #D60093, #6A0DAD)",
        x: 750,
        y: 80,
    },
    {
        id: 8,
        nome: "Jedha",
        imagemPlaneta: "assets/images/Jedha_TypeScript.png",
        descricao: "Jedha, a fonte do Cristal Kyber e da estrutura de crença Jedi, representa o TypeScript: a linguagem que traz ordem, tipagem e fundação robusta ao JavaScript, garantindo a solidez e a previsibilidade essenciais para grandes projetos.",
        linguagem: "TypeScript",
        iconeLinguagem: "assets/images/Icone_TypeScript.png",
        corModal: "linear-gradient(90deg, #2980B9, #4A4A4A)",
        x: 670,
        y: 280,
    },
    {
        id: 9,
        nome: "Lah'mu",
        imagemPlaneta: "assets/images/Lah'mu_Flutter.png",
        descricao: "Lah'mu, com sua paisagem isolada e versátil, representa o Flutter: o framework que oferece uma tela totalmente limpa e modular para construir interfaces nativas e esteticamente belas em qualquer plataforma, garantindo refúgio e funcionalidade onde quer que o código seja levado.",
        linguagem: "Flutter",
        iconeLinguagem: "assets/images/Icone_Flutter.png",
        corModal: "linear-gradient(90deg, #36332E, #1E8449)",
        x: 980,
        y: 90,
    },
    {
        id: 10,
        nome: "Endor",
        imagemPlaneta: "assets/images/Endor_Python.png",
        descricao: "Endor, com sua natureza expansiva e comunidade acolhedora (os Ewoks!), representa o Python: uma linguagem acessível e versátil, perfeita para construir a lógica de BackEnd de forma legível e poderosa, pronta para qualquer tarefa, do básico ao complexo.",
        linguagem: "Python",
        iconeLinguagem: "assets/images/Icone_Python.png",
        corModal: "linear-gradient(90deg, #003300, #654321)",
        x: 120,
        y: 680,
    },
    {
        id: 11,
        nome: "Corellia",
        imagemPlaneta: "assets/images/Corellia_Django.png",
        descricao: "Corellia, o berço de naves icônicas e engenheiros pragmáticos, representa o Django: o framework Python que acelera o desenvolvimento BackEnd, fornecendo uma estrutura completa e 'baterias incluídas' para construir aplicações web robustas e funcionais em tempo recorde.",
        linguagem: "Django",
        iconeLinguagem: "assets/images/Icone_Django.png",
        corModal: "linear-gradient(90deg, #A52A2A, #4B4B4B)",
        x: 320,
        y: 550,
    },
    {
        id: 12,
        nome: "Kessel",
        imagemPlaneta: "assets/images/Kessel_FastAPI.png",
        descricao: "Kessel, o local da Rota lendária onde cada segundo conta, representa o FastAPI: o framework Python moderno que utiliza tipagem e programação assíncrona para garantir APIs de BackEnd com performance e velocidade excepcionais, ideal para a transferência de dados em alta velocidade.",
        linguagem: "FastAPI",
        iconeLinguagem: "assets/images/Icone_FastAPI.png",
        corModal: "linear-gradient(90deg, #8B0000, #333333)",
        x: 1120,
        y: 300,
    },
    {
        id: 13,
        nome: "Ryloth",
        imagemPlaneta: "assets/images/Ryloth_Java.png",
        descricao: "Ryloth, com seu ciclo de dia/noite complexo e a resiliência de seu povo, representa o Java: uma linguagem madura, robusta e orientada a objetos, construída para operar com estabilidade e portabilidade em qualquer ambiente de BackEnd.",
        linguagem: "Java",
        iconeLinguagem: "assets/images/Icone_Java.png",
        corModal: "linear-gradient(90deg, #E67E22, #553C00)",
        x: 650,
        y: 500,
    },
    {
        id: 14, 
        nome: "Felúcia",
        imagemPlaneta: "assets/images/Felucia_Dart.png",
        descricao: "Felúcia, um mundo de ecossistemas únicos e adaptações complexas, representa o Dart: a linguagem versátil e concisa que se adapta tanto ao FrontEnd (com Flutter) quanto ao BackEnd, oferecendo uma experiência de código moderna e elegante.",
        linguagem: "Dart",
        iconeLinguagem: "assets/images/Icone_Dart.png",
        corModal: "linear-gradient(90deg,  #3CB371, #1A2D44)",
        x: 910,
        y: 460,
    },
    {
        id: 15,
        nome: "Chandrila",
        imagemPlaneta: "assets/images/Chandrila_Figma.png",
        descricao: "Chandrila, com sua importância política e foco em consenso e colaboração, representa o Figma: a ferramenta central de design onde a equipe inteira (devs, designers e stakeholders) converge para criar, prototipar e evoluir a interface do usuário em tempo real.",
        linguagem: "Figma",
        iconeLinguagem: "assets/images/Icone_Figma.png",
        corModal: "linear-gradient(90deg, #696969, #006064)",
        x: 520,
        y: 700,
    },
    {
        id: 16,
        nome: "Bespin",
        imagemPlaneta: "assets/images/Bespin_Canva.png",
        descricao: "Bespin, a Cidade das Nuvens que oferece uma visão ampla e acessível do céu, representa o Canva: a ferramenta que democratiza o design, permitindo a criação rápida e visualmente atrativa de qualquer recurso de FrontEnd, com total leveza e visibilidade.",
        linguagem: "Canva",
        iconeLinguagem: "assets/images/Icone_Canva.png",
        corModal: "linear-gradient(90deg, #FF7F50, #151B54)",
        x: 800,
        y: 660,
    },
    {
        id: 17,
        nome: "Polis Massa",
        imagemPlaneta: "assets/images/Polis_Massa_Vite.png",
        descricao: "Polis Massa, o posto avançado conciso e funcional focado em observação e agilidade, representa o Vite: a ferramenta que transforma o desenvolvimento FrontEnd com sua velocidade relâmpago, simplificando o bundling e garantindo a construção instantânea de projetos.",
        linguagem: "Vite",
        iconeLinguagem: "assets/images/Icone_Vite.png",
        corModal: "linear-gradient(90deg, #404040, #00BFFF)",
        x: 980,
        y: 700,
    },
    {
        id: 18,
        nome: "Fondor",
        imagemPlaneta: "assets/images/Fondor_DRF.png",
        descricao: "Fondor, o estaleiro que transforma navios brutos em frotas funcionais, representa o Django REST Framework: a poderosa extensão que transforma um projeto Django comum em uma API REST coesa, organizada e pronta para consumo por qualquer aplicação FrontEnd.",
        linguagem: "Django Rest Framework",
        iconeLinguagem: "assets/images/Icone_DRF.png",
        corModal: "linear-gradient(90deg, #525252, #FF4500)",
        x: 1100,
        y: 550,
    },
    {
        id: 19,
        nome: "Scarif",
        imagemPlaneta: "assets/images/Scarif_Banco_Dados.png",
        descricao: "Scarif, o mundo-cofre que armazena os planos essenciais da Estrela da Morte, representa o Banco de Dados: o sistema vital que organiza, armazena e protege todos os dados estruturais e operacionais, sendo a fundação para a lógica de BackEnd e a exibição do FrontEnd.",
        linguagem: "Banco de dados (geral)",
        iconeLinguagem: "assets/images/Icone_MySQL.png",
        corModal: "linear-gradient(90deg, #006400, #5D5C61)",
        x: 890,
        y: 250,
    },
]