// Criando uma lista de projetos para melhor manipulação
export const projetos = [
    {
        "id": 1,
        "nomeProjeto": "MineLucas",
        "holocronJedi": "assets/images/Holocron_Jedi.png",
        "holocronSith": "assets/images/Holocron_Sith.png",
        "logoProjeto": "assets/images/Logo_MineLucas.png",
        "descricaoProjeto": "A MineLucas foi um projeto divertido para se fazer! Nessa missão, eu explorei diversos planetas para conseguir construir uma API, no Django, encontrado no planeta Corellia, de Minecraft. Porém não era suficiente. Eu queria integrar com o React que, assim como o Django, é outro framework/biblioteca poderosa encontrada no planeta Kamino, e assim, consegui unir os dois em dois holocrons distintos: Jedi e Sith, pelo equilíbrio da força, e também, por causa do tamanho que o projeto ficou, é claro. Veja o vídeo abaixo para ver como ficou o resultado final:",
        // "video": "assets/videos/MineLucas.mp4",
        "ferramentas": [
            "assets/images/Icone_React.png",
            "assets/images/Icone_HTML.png",
            "assets/images/Icone_CSS.png",
            "assets/images/Icone_Python.png",
            "assets/images/Icone_Django.png",
            "assets/images/Icone_Tailwind.png",
            "assets/images/Icone_Canva.png",
        ],
    },
    {
        "id": 2,
        "nomeProjeto": "Kanbucas",
        "holocronJedi": "assets/images/Holocron_Jedi.png",
        "holocronSith": "assets/images/Holocron_Sith.png",
        "logoProjeto": "assets/images/Logo_Kanbucas.png",
        "descricaoProjeto": "A Kanbucas foi um projeto no qual exploramos MUITO o planeta Kamino e de Corellia, em busca de acessibilidade e de um Kanban com muito estilo! Foi complicado, foram diversas missões que variam entre configurar o Django e até colocar ARIA e acessibilidade 100% no projeto. A missão foi concluída com sucesso, então caso você tenha se interessado, veja o vídeo abaixo para ver como ficou o resultado final:",
        // "video": "assets/videos/MineLucas.mp4",
        "ferramentas": [
            "assets/images/Icone_React.png",
            "assets/images/Icone_HTML.png",
            "assets/images/Icone_SASS.png",
            "assets/images/Icone_Python.png",
            "assets/images/Icone_Django.png",
            "assets/images/Icone_SQLite.png",
            "assets/images/Icone_Canva.png",
            "assets/images/Icone_Node.png",
            "assets/images/Icone_Vite.png",
            "assets/images/Icone_DRF.png",
        ],
    },
]